# Generated by Django 4.2.10 on 2024-03-08 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('encrypted_image', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='DecryptedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decrypted_image', models.BinaryField()),
                ('encrypted_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.encryptedimage')),
            ],
        ),
    ]
