# Generated by Django 4.2.10 on 2024-03-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encryptedimage',
            old_name='encrypted_image',
            new_name='key',
        ),
        migrations.AlterField(
            model_name='encryptedimage',
            name='image',
            field=models.ImageField(upload_to='encrypted_images/'),
        ),
        migrations.DeleteModel(
            name='DecryptedImage',
        ),
    ]
